export { default as Login } from './Login'
export { default as Home } from './Home'
export { default as Products } from './Products'
export { default as Categories } from './Categories'
export { default as Users } from './Users'
export { default as Profile } from './Profile'